### ISSUE TITLE
replace Arrowhead Framework with Eclipse Arrowhead

### ISSUE THREAD

**Issue by BlackRose01** [eclipse-arrowhead/documentation#4]
Hello,

the name of the framework changed to Eclipse Arrowhead when it was moved to the Eclipse Foundation. So please rename "Arrowhead Framework" with "Eclipse Framework".

Kind Regards,
BlackRose

**Comment by jerkerdelsing** [comment]
Could you be m ore specific on where in the documents Arrowhead Framework is used?

**Comment by BlackRose01** [comment]
1 Introduction: 2. paragraph
1.1 Primary Audiences: 2. point
1.2 Scope: 1. sentence
1.4 Relationships to Other Documents: IoT Automation: Arrowhead Framework -> 1. sencence
2 Overview: 1. sentence

and so on

**Comment by emanuelpalm** [comment]
My impression was that the term "Arrowhead Framework" is to be used also in the future, even though the name "Eclipse Arrowhead" should be given more prominence. I figured that Eclipse Arrowhead is a framework, which means that it is still correct to call it as such. @jerkerdelsing Is this something you would like me to correct?

**Comment by jerkerdelsing** [comment]
The approach I have used is Eclipse Arrowhead, Eclipse Arrowhead Framework or Arrowhead framework. Soo framework with an f not an F.
